name: test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- macOS-latest
          #- windows-latest
        raku-version:
          #- 'latest'
          - '2021.12'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Linux specific setup
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get install -y libfribidi-dev
          wget https://github.com/harfbuzz/harfbuzz/archive/3.3.1.tar.gz
          (tar xzf 3.3.1.tar.gz && cd harfbuzz-3.3.1 && ./autogen.sh && make)
          ## Requires future Debian; v12+?
          ##sudo apt-get install -y libharfbuzz-dev
      - name: macOS specific setup
        if: contains(matrix.os, 'macOS')
        run: |
          brew update
          ## brew install autoconf automake libtool
          brew install harfbuzz
          brew install fribidi
      - name: Install Dependencies
        run: |
          export LD_LIBRARY_PATH=`pwd`/harfbuzz-3.3.1/src/.libs
          zef install --/test App::Prove6
          # currently developing against the Cairo 'tags-and-toc' branch
          (git clone -b tags-and-toc https://github.com/timo/cairo-p6 && cd cairo-p6 && zef install .)
          # also dependant on unreleased PDF::Tags::Reader changes
          (git clone https://github.com/pdf-raku/PDF-Tags-Reader-raku && cd PDF-Tags-Reader-raku && zef install .)
          zef --deps-only install .
      - name: Run Tests
        run: |
          export LD_LIBRARY_PATH=`pwd`/harfbuzz-3.3.1/src/.libs
          prove6 -I. t
          zef install .
